import { apiServices } from '@/services';
import { FormFieldProps } from '@/utils/form/mount-form';
import { states } from '@/utils/mocks/states';

export const clinicFormFields = {
  basicData: [
    {
      type: 'input',
      name: 'fantasyName',
      title: 'Nome Fantasia',
      placeholder: 'Espaço Arieli Antonelo',
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'name',
      title: 'Nome Completo',
      placeholder: 'Arieli Antonelo',
      rowSize: 6,
    },
    {
      type: 'input-document',
      name: 'document',
      title: 'CPF / CNPJ',
      placeholder: '000.000.000-00',
      rowSize: 6,
    },
    {
      type: 'input-mask',
      name: 'birthdate',
      title: 'Nascimento',
      placeholder: '01/01/2000',
      mask: '99/99/9999',
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'email',
      title: 'E-mail',
      placeholder: 'arili_rbd@hotmail.com',
      rowSize: 6,
    },
    {
      type: 'input-mask',
      name: 'phone',
      title: 'Celular',
      placeholder: '(11) 99999-9999',
      mask: '(99) 99999-9999',
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'city',
      title: 'Cidade',
      placeholder: 'Bragança Paulista',
      rowSize: 4,
    },
    {
      type: 'select',
      name: 'state',
      title: 'Estado',
      placeholder: 'São Paulo',
      rowSize: 4,
      selectOptions: states,
    },
    {
      type: 'input',
      name: 'habitantsCount',
      title: 'Nro Habitantes',
      placeholder: '170.000',
      rowSize: 4,
    },
    {
      type: 'autocomplete-multiple',
      name: 'expertiseId',
      title: 'Atuação',
      placeholder: 'Atuação',
      autocompleteFn: apiServices.clinics.expertise.list,
      rowSize: 12,
      selectOptions: [],
    },
    {
      type: 'input',
      name: 'observations',
      title: 'Observações',
      placeholder: 'Observações gerais',
      rowSize: 12,
    },
  ] as FormFieldProps[],
  contract: [
    {
      type: 'autocomplete',
      name: 'userAttendanceId',
      title: 'Anjo',
      placeholder: 'Anjo',
      rowSize: 12,
      autocompleteFn: apiServices.angel.list,
      autocompleteLabel: 'name',
    },
    {
      type: 'input-date',
      name: 'startContract',
      title: 'Início do Contrato',
      placeholder: '01/01/2023',
      dateFormat: 'dd/MM/yyyy',
      rowSize: 6,
    },
    {
      type: 'input-date',
      name: 'endContract',
      title: 'Fim do Contrato',
      placeholder: '01/01/2024',
      dateFormat: 'dd/MM/yyyy',
      rowSize: 6,
    },
    {
      type: 'input-numeric',
      name: 'accumulativeTime',
      title: 'Tempo Acumulado (em dias)',
      placeholder: '150',
      rowSize: 6,
    },
    {
      type: 'input-numeric',
      name: 'projectTime',
      title: 'Tempo de Projeto (em dias)',
      placeholder: '250',
      rowSize: 6,
    },
    {
      type: 'select',
      name: 'status',
      title: 'Status do Contrato',
      placeholder: 'Status do Contrato',
      selectOptions: [],
      rowSize: 12,
    },
    {
      type: 'autocomplete',
      name: 'categoryId',
      title: 'Categoria',
      placeholder: 'Categoria',
      rowSize: 12,
      autocompleteFn: apiServices.categories.list,
      autocompleteLabel: 'name',
    },
  ] as FormFieldProps[],
  billings: [
    {
      type: 'input-currency',
      name: 'initialAverageRevenue',
      title: 'Faturamento Médio Inicial',
      placeholder: 'R$ 5.000,00',
      rowSize: 6,
    },
    {
      type: 'input-currency',
      name: 'afterAverageRevenue',
      title: 'Faturamento Máximo - Depois dos anjos',
      placeholder: 'R$ 15.000,00',
      rowSize: 6,
    },
    {
      type: 'select',
      name: 'increaseRevenue',
      title: 'Aumentou Faturamento',
      placeholder: 'Aumentou Faturamento',
      selectOptions: [
        { value: true, label: 'Sim' },
        { value: false, label: 'Não' },
      ],
      rowSize: 6,
    },
    {
      type: 'input-number',
      name: 'growthRate',
      title: 'Taxa de Crescimento (%)',
      placeholder: '150%',
      rowSize: 6,
    },
    {
      type: 'input-currency',
      name: 'initialRevenue',
      title: 'Faturamento Inicial',
      placeholder: 'R$ 5.000,00',
      rowSize: 6,
    },
    {
      type: 'input-currency',
      name: 'startValue',
      title: 'Caixa Inicial',
      placeholder: 'R$ 8.000,00',
      rowSize: 6,
    },
  ] as FormFieldProps[],
};
