import { apiServices } from '@/services';
import { FormFieldProps } from '@/utils/form/mount-form';
import { states } from '@/utils/mocks/states';

export const clinicFormFields = {
  basicData: [
    {
      type: 'input',
      name: 'fantasyName',
      title: 'Nome Fantasia',
      placeholder: 'Informe o nome da clínica',
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'name',
      title: 'Nome Completo',
      placeholder: 'Informe o nome completo',
      rowSize: 6,
    },
    {
      type: 'input-document',
      name: 'document',
      title: 'CPF / CNPJ',
      placeholder: 'Informe o CPF ou CNPJ',
      rowSize: 6,
    },
    {
      type: 'input-date',
      name: 'birthDate',
      title: 'Nascimento',
      placeholder: 'Informe a data de nascimento',
      dateFormat: 'dd/MM/yyyy',
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'email',
      title: 'E-mail',
      placeholder: 'Informe o e-mail',
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'instagram',
      title: 'Instagram',
      placeholder: 'Informe o instagram sem o @',
      rowSize: 6,
    },
    {
      type: 'input-mask',
      name: 'phone',
      title: 'Celular',
      placeholder: 'Informe o telefone ou whatsapp',
      mask: '(99) 99999-9999',
      rowSize: 4,
    },
    {
      type: 'input',
      name: 'city',
      title: 'Cidade',
      placeholder: 'Informe a cidade',
      rowSize: 4,
    },
    {
      type: 'select',
      name: 'state',
      title: 'Estado',
      placeholder: 'Selecione o estado',
      rowSize: 2,
      selectOptions: states,
    },
    {
      type: 'input',
      name: 'habitantsCount',
      title: 'Nro Habitantes',
      placeholder: 'Informe a quantidade de habitantes',
      rowSize: 2,
    },
    {
      type: 'autocomplete-multiple',
      name: 'expertiseId',
      title: 'Atuação',
      placeholder: 'Selecione a área de atuação',
      autocompleteFn: apiServices.clinics.expertise.list,
      rowSize: 12,
      selectOptions: [],
    },
    {
      type: 'input',
      name: 'observations',
      title: 'Observações',
      placeholder: 'Observações gerais',
      rowSize: 12,
    },
  ] as FormFieldProps[],
  contract: [
    {
      type: 'autocomplete',
      name: 'userAttendanceId',
      title: 'Anjo',
      placeholder: 'Selecione o anjo responsável',
      rowSize: 12,
      autocompleteFn: apiServices.angel.list,
      autocompleteLabel: 'name',
    },
    {
      type: 'input-date',
      name: 'startContract',
      title: 'Início do Contrato',
      placeholder: 'Informe a data de início do contrato',
      dateFormat: 'dd/MM/yyyy',
      rowSize: 6,
    },
    {
      type: 'input-date',
      name: 'endContract',
      title: 'Fim do Contrato',
      placeholder: 'Informe a data de fim do contrato',
      dateFormat: 'dd/MM/yyyy',
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'accumulativeTime',
      title: 'Tempo Acumulado (em dias)',
      readonly: true,
      placeholder: 'Calculado automáticamente',
      disabled: true,
      rowSize: 6,
    },
    {
      type: 'input',
      name: 'projectTime',
      title: 'Tempo de Projeto (em dias)',
      readonly: true,
      placeholder: 'Calculado automáticamente',
      rowSize: 6,
    },
    {
      type: 'select',
      name: 'contractStatus',
      title: 'Status do Contrato',
      placeholder: 'Status do Contrato',
      selectOptions: [
        { value: 'ACTIVE', label: 'Ativo' },
        { value: 'INACTIVE', label: 'Inativo' },
        { value: 'BLOCKED', label: 'Bloqueado' },
        { value: 'GUIVENUP', label: 'Desistiu' },
        { value: 'EXPIRATION', label: 'Expirou' },
      ],
      rowSize: 12,
    },
    {
      type: 'autocomplete',
      name: 'categoryId',
      title: 'Categoria',
      placeholder: 'Selecione a categoria do cliente',
      rowSize: 12,
      autocompleteFn: apiServices.categories.list,
      autocompleteLabel: 'name',
    },
    {
      type: 'label',
      title: 'Produtos Adquiridos',
      placeholder: 'Produtos Adquiridos',
      rowSize: 12,
    },
    {
      type: 'checkbox',
      name: 'rykaAssessoria',
      title: 'Ryka Assessoria',
      placeholder: 'Ryka Assessoria',
      rowSize: 4,
    },
    {
      type: 'checkbox',
      name: 'impulse',
      title: 'Impulse',
      placeholder: 'Impulse',
      rowSize: 4,
    },
    {
      type: 'checkbox',
      name: 'anjosSystem',
      title: 'System',
      placeholder: 'System',
      rowSize: 4,
    },
  ] as FormFieldProps[],
  billings: [
    {
      type: 'input-currency',
      name: 'initialAverageRevenue',
      title: 'Faturamento Médio Inicial',
      placeholder: 'Faturamento médio inicial',
      rowSize: 6,
    },
    {
      type: 'input-currency',
      name: 'afterAverageRevenue',
      title: 'Faturamento Máximo - Depois dos anjos',
      placeholder: 'Qual o maior faturamento, depois dos anjos?',
      rowSize: 6,
    },
    {
      type: 'select',
      name: 'increaseRevenue',
      title: 'Aumentou Faturamento',
      placeholder: 'A protegida aumentou o faturamento?',
      selectOptions: [
        { value: true, label: 'Sim' },
        { value: false, label: 'Não' },
      ],
      rowSize: 6,
    },
    {
      type: 'input-number',
      name: 'growthRate',
      title: 'Taxa de Crescimento (%)',
      placeholder: 'Informe a taxa de crescimento da protegida',
      rowSize: 6,
    },
    {
      type: 'input-currency',
      name: 'initialRevenue',
      title: 'Faturamento Inicial',
      placeholder: 'Qual o faturamento inicial da protegida?',
      rowSize: 6,
    },
    {
      type: 'input-currency',
      name: 'startValue',
      title: 'Caixa Inicial',
      placeholder: 'Qual o valor inicial do caixa da protegida?',
      rowSize: 6,
    },
  ] as FormFieldProps[],
};
